@startchen classroom_system

<style>
.entity {
  BackGroundColor #E2EFDA
  FontColor black
}
.relationship {
  BackGroundColor #DAE8FC
  FontColor black
}
.key {
  FontStyle bold
  TextDecoration underline
}
</style>

entity "User" as USER <<entity>> {
  "user_id" as UserID <<key>>
  username
  password
  firstname
  lastname
  email
  auth_type
}

entity "Workspace" as WORKSPACE <<entity>> {
  "workspace_id" as WorkspaceID <<key>>
  name
  description
  join_code
  created_at
  "created_by" as CreatedByFK <<foreign key to User>>
}

entity "Workspace_Member" as WORKSPACE_MEMBER <<entity>> {
  "member_id" as MemberID <<key>>
  "user_id" as UserIDFK <<foreign key to User>>
  "workspace_id" as WorkspaceIDFK <<foreign key to Workspace>>
  role
}

entity "News" as NEWS <<entity>> {
  "news_id" as NewsID <<key>>
  "workspace_id" as WorkspaceIDFK <<foreign key to Workspace>>
  title
  content
  created_at
  "created_by" as CreatedByFK <<foreign key to User>>
}

entity "Comment" as COMMENT <<entity>> {
  "comment_id" as CommentID <<key>>
  "news_id" as NewsIDFK <<foreign key to News>>
  "user_id" as UserIDFK <<foreign key to User>>
  content
  created_at
}

entity "Like" as LIKE <<entity>> {
  "like_id" as LikeID <<key>>
  "news_id" as NewsIDFK <<foreign key to News>>
  "user_id" as UserIDFK <<foreign key to User>>
  liked_at
}

entity "Assignment" as ASSIGNMENT <<entity>> {
  "assignment_id" as AssignmentID <<key>>
  "workspace_id" as WorkspaceIDFK <<foreign key to Workspace>>
  title
  description
  due_date
  "created_by" as CreatedByFK <<foreign key to User>>
}

entity "Assignment_Submission" as ASSIGNMENT_SUBMISSION <<entity>> {
  "submission_id" as SubmissionID <<key>>
  "assignment_id" as AssignmentIDFK <<foreign key to Assignment>>
  "user_id" as UserIDFK <<foreign key to User>>
  submission_date
  score
}

relationship "is_member_of" as IS_MEMBER <<relationship>> {
}
USER -1- IS_MEMBER
IS_MEMBER =N= WORKSPACE_MEMBER

relationship "belongs_to" as BELONGS_TO <<relationship>> {
}
WORKSPACE =1= BELONGS_TO
BELONGS_TO =N= WORKSPACE_MEMBER

relationship "contains" as CONTAINS_NEWS <<relationship>> {
}
WORKSPACE -1- CONTAINS_NEWS
CONTAINS_NEWS =N= NEWS

relationship "has" as HAS_ASSIGNMENT <<relationship>> {
}
WORKSPACE -1- HAS_ASSIGNMENT
HAS_ASSIGNMENT =N= ASSIGNMENT

relationship "submits" as SUBMITS <<relationship>> {
}
USER -1- SUBMITS
SUBMITS =N= ASSIGNMENT_SUBMISSION

relationship "contains" as CONTAINS_SUBMISSION <<relationship>> {
}
ASSIGNMENT -1- CONTAINS_SUBMISSION
CONTAINS_SUBMISSION =N= ASSIGNMENT_SUBMISSION

relationship "creates" as CREATES <<relationship>> {
}
USER -1- CREATES
CREATES =N= WORKSPACE

relationship "creates" as CREATES_NEWS <<relationship>> {
}
USER -1- CREATES_NEWS
CREATES_NEWS =N= NEWS

relationship "creates" as CREATES_ASSIGNMENT <<relationship>> {
}
USER -1- CREATES_ASSIGNMENT
CREATES_ASSIGNMENT =N= ASSIGNMENT

relationship "comments_on" as COMMENTS_ON <<relationship>> {
}
USER -1- COMMENTS_ON
COMMENTS_ON =N= COMMENT

relationship "has_comments" as HAS_COMMENTS <<relationship>> {
}
NEWS -1- HAS_COMMENTS
HAS_COMMENTS =N= COMMENT

relationship "likes" as LIKES <<relationship>> {
}
USER -1- LIKES
LIKES =N= LIKE

relationship "has_likes" as HAS_LIKES <<relationship>> {
}
NEWS -1- HAS_LIKES
HAS_LIKES =N= LIKE

@endchen